apiVersion: v1
entries:
  uptimerobot-operator:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-02-02T22:58:44.768014858Z"
    description: A Kubernetes operator that creates uptime monitors for your ingresses
    digest: 972e25bc7967fec77ccaa2d64bc29b4718573a8b5b7dc4b840855c2589986219
    name: uptimerobot-operator
    type: application
    urls:
    - https://brennerm.github.io/uptimerobot-operator/helm/uptimerobot-operator-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-02T22:58:44.767371153Z"
